apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      imagePullSecrets:
        - name: docker-hub-image-secret
      containers:
      - name: spring-boot-app
        image: neonvignesh/enrichprojects:cicd-test-1-13
        ports:
        - containerPort: 8080
